name: CI Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep "versionName" app/build.gradle | awk -F"'" '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew assembleDebug --parallel --build-cache

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KeyAttestation-${{ steps.get_version.outputs.VERSION }}-debug
          path: app/build/outputs/apk/debug/*.apk
